# Generated by Django 5.2.7 on 2025-10-08 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRitiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('durata_minuti', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('data_preferita', models.DateField()),
                ('ora_preferita', models.TimeField()),
                ('marca_racchetta', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('confermata', 'Confermata'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='in_attesa', max_length=20)),
                ('creato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('punto_ritiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenotazioni.puntoritiro')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenotazioni.servizio')),
            ],
        ),
    ]
