# Generated by Django 5.2.7 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='puntoritiro',
            options={'verbose_name': 'Punto di Ritiro', 'verbose_name_plural': 'Punti di Ritiro'},
        ),
        migrations.AlterModelOptions(
            name='servizio',
            options={'verbose_name': 'Servizio', 'verbose_name_plural': 'Servizi'},
        ),
        migrations.RemoveField(
            model_name='servizio',
            name='durata_minuti',
        ),
        migrations.AddField(
            model_name='servizio',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
    ]
